### ISSUE TITLE
Missing compatibility with Truffle build output

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-propeller-core#16]
There are some discrepancies with the compilation output of Truffle:
- CompilationResult class expects the output to be a map of contracts, that is not true for Truffle (output is a single contract). Easy to fix adding method parse() to SolidityContractDetails
- abi field is an array rather than a String
- ... might be more, couldn't go further

**Comment by kivanov82** [comment]
[SmartToken.json.zip](https://github.com/adridadou/eth-propeller-core/files/1941569/SmartToken.json.zip)

**Comment by adridadou** [comment]
done
