### ISSUE TITLE
Feature: Replay blocks

### ISSUE THREAD

**Issue by ESchouten** [adridadou/eth-propeller-core#17]
When the client has been offline, replaying all blocks mined since is necessary to handle events emitted in smart contracts the application is subscribed to.

**Comment by ESchouten** [comment]
Might only be relevant in combination with the web3j connector, since EthereumJ is ran internally, so might not have these issues (?)

**Comment by adridadou** [comment]
It is a good point. But it needs to be configurable. It is interesting to imagine being able to say "I want from this block number" and everything is being replayed. Is this what you had in mind or something else? And yes ethj does it automatically

**Comment by ESchouten** [comment]
Yeah, programmatically start replaying blocks/events from a certain block number to prevent missed events in an external application, or just to rebuild/verify its local database.

**Comment by adridadou** [comment]
I wouldn't implement that for ethj but more for web3j only.
The reason I don't want to do that as a generic solution is:
- Ethereumj doesn't really need that because it plays every blocks when it syncs after being offline
- Because it wouldn't work for Test blockchain

I propose to do that in the EthereumRpcConfig where you can say that you want to read from a particular block number

config.fromBlock(12345667) // by default, from latest

and this will start reading the block at startup

**Comment by ESchouten** [comment]
Tend to agree with that, only reason I can think of why you would want to replay blocks in EthJ is when you subscribe to events thrown from a contract and you want to build your current state database with events thrown from the start of the contract, before you were listening.

**Comment by adridadou** [comment]
do you think this is still relevant ?

**Comment by ESchouten** [comment]
Currently, instead of replaying blocks, I am pulling states directly from the smart contract, which is probably a lot more efficient than querying and replaying tens/hundreds of thousands of blocks.

As for thrown events, they are stored in the smart contract itself after processing and can be queried using web3. Currently, we are testing an implementation doing this via Propeller, so we can synchronize our local state via events as well.

So as far as our application goes, no.

**Comment by adridadou** [comment]
yes def. Ok So I'm closing that for now. we can always re-open if needed
