### ISSUE TITLE
Missing support of 'signature' field in ABI

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-propeller-core#18]
Latest Solidity compiler adds new field 'signature' to the API specification.
Currently this leads to the "error while deserialising ABI" exception when trying to work with the contracts.

**Comment by adridadou** [comment]
I was going to update the infura integration today so I can do that too.
What is this field about? Do u have a link to some documentation?

Le lun. 24 sept. 2018 à 11:44, Kiril Ivanov <notifications@github.com> a
écrit :

**Comment by kivanov82** [comment]
Cool, here is the spec:
https://solidity.readthedocs.io/en/develop/abi-spec.html

Would than be possible to fix https://github.com/adridadou/eth-propeller-core/issues/16 too?
It's a small change but prevents using the solidity compiler output for propeller as-is.

**Comment by adridadou** [comment]
I'll have a look and do my best to solve that too

Le lun. 24 sept. 2018 à 11:55, Kiril Ivanov <notifications@github.com> a
écrit :
