### ISSUE TITLE
replace my ugly while(true) with observables

### ISSUE THREAD

**Issue by adridadou** [adridadou/eth-propeller-core#8]
We have different issues with the way futures, async etc is being handled in eth-propeller

The idea would be to do the following:
- having a queue of transactions that need to be handled
- a consumer that takes those transactions and send them to the network
- an observer that will listen to new blocks and will check whether the transaction has been added for each of them

This means removing the while(true) completely and use Observable (we should upgrade to RxJava 2.0)

Also to take into account, the transaction consumer needs to be single threaded, or at least single threaded for a particular private key, so it can effectively do nonce calculation and never create a bad nonce

**Comment by fforbeck** [comment]
I started playing with this issue and changed to RxJava 2.0. It breaks the current implementation of Observables and Subscribers. Besides that, the Web3J also needs to be updated to 4.1.1.
